### ISSUE TITLE
Delegator containers are not stable

### ISSUE THREAD

**Issue by joelchen** [tearust/teaproject#85]
Containers in a delegator crashed:
```
CONTAINER ID   IMAGE                                       COMMAND                  CREATED        STATUS                         PORTS                                                                                                                                 NAMES
71f526635470   tearust/adapter:epoch5-0.4                  "/bin/sh -c '/wait &…"   41 hours ago   Up 41 hours                    0.0.0.0:5011->5011/tcp, :::5011->5011/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                  delegate-adapter
0251f1b08106   tearust/tea-orbit-db-http-api:v0.0.8        "docker-entrypoint.s…"   41 hours ago   Restarting (1) 9 seconds ago                                                                                                                                         delegate-orbitdb
e1c50a90d393   tearust/vmh-server:epoch5-0.1               "/bin/sh -c '/wait &…"   41 hours ago   Up 41 hours                                                                                                                                                          delegate-vmh
8c8baf6fd5e6   tearust/tea-camellia:fast-0.5.1             "bash -c 'tea-camell…"   41 hours ago   Up 41 hours                    0.0.0.0:9933->9933/tcp, :::9933->9933/tcp, 0.0.0.0:9944->9944/tcp, :::9944->9944/tcp, 0.0.0.0:30332->30333/tcp, :::30332->30333/tcp   delegate-layer1
36ce187d071a   tearust/nsm-simulator:layer2-0.3            "/bin/sh -c /tearust…"   41 hours ago   Up 41 hours                                                                                                                                                          delegate-nsm
f523d56747c4   tearust/runtime:epoch5-0.1                  "/bin/sh -c /tearust…"   41 hours ago   Up 41 hours                                                                                                                                                          delegate-runtime
c69b5b3631a5   ipfs/go-ipfs:v0.8.0                         "sh -c '/ipfs/config…"   41 hours ago   Exited (137) 3 hours ago                                                                                                                                             delegate-ipfs
25be38f6cd4d   tearust/parent-instance-client:epoch5-0.1   "/bin/sh -c '/wait &…"   41 hours ago   Up 41 hours                                                                                                                                                          delegate-parent
```
Viewing logs of go-ipfs container:
```
# docker logs c69b5b3631a5
Changing user to ipfs
ipfs version 0.8.0
generating ED25519 keypair...done
peer identity: 12D3KooWJWp5YSt1ModyBVkt213pwfJpVn7yCZcZ3DkCzuQDbQAe
initializing IPFS node at /data/ipfs
to get started, enter:

	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme

2021-10-24T09:21:06.091Z	ERROR	provider.queue	Failed to enqueue cid: leveldb: closed
Copying swarm key from file...
ipfs version 0.8.0
Found IPFS fs-repo at /data/ipfs
added /ip4/64.227.105.212/tcp/4001/p2p/12D3KooWBXnrRWGMNkE8to5fnD9Z1j9NhTXSxWHkP7ZM648BgD3E
added /ip4/164.90.159.26/tcp/4001/p2p/12D3KooWHqVAepKJobXuRZ5btyDdaNMgS3X1iDaMx6yY7TFHG9sh
Initializing daemon...
go-ipfs version: 0.8.0-ce693d7
Repo version: 11
System version: amd64/linux
Golang version: go1.14.4
Swarm is limited to private network of peers with the swarm key
Swarm key fingerprint: 84745f93695d344e585d681cd80cfce0
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.18.0.2/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.18.0.2/tcp/4001
API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://0.0.0.0:5001/webui
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
Daemon is ready
```
Viewing logs of tea-orbit-db-http-api container (duplicates removed):
```
# docker logs 0251f1b08106
SEED => 
ADMIN_LIST => 
orbitdb_opts => {
  directory: '/orbitdb',
  identity: Identity {
    _id: '0342bf1eafacd66f2a4b8b2c291a45d1c74678ce4c1692a31dab8369b247d97a5f',
    _publicKey: '0497d1f171c50198c7875b75f29022414b66a75f2dc72969046028067443483cf01ee72c679f8016728c5fa91264a75bb83ffe59a7ffd16ba610a7cb77426a13ab',
    _signatures: {
      id: '3045022100f4b0afe6fa1741fe53d16b9b8633cf917327fa64d047f89d0850d9138bd8f0b20220435485663b5d89600d40246b0eebf1d6a5d2a14e07e60b50d42ad53d970dde05',
      publicKey: '3045022100a4964e0b8b630f3431485686b8ee2cdf1f8cf9da69c83bc69914178bc61c609902203f31ca95bbcaf923b327d6834f18bd01bfc80825684f6029bc3e1b576cf472e4'
    },
    _type: 'orbitdb',
    _provider: Identities {
      _keystore: [Keystore],
      _signingKeystore: [Keystore],
      _knownIdentities: [LRU]
    }
  },
  AccessControllers: [class AccessControllers]
}
FetchError: request to http://ipfs:5001/api/v0/id failed, reason: connect ECONNREFUSED 172.18.0.2:5001
    at ClientRequest.<anonymous> (/api/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:369:20)
    at Socket.socketErrorListener (node:_http_client:472:9)
    at Socket.emit (node:events:369:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
SEED => 
ADMIN_LIST => 
orbitdb_opts => {
  directory: '/orbitdb',
  identity: Identity {
    _id: '0342bf1eafacd66f2a4b8b2c291a45d1c74678ce4c1692a31dab8369b247d97a5f',
    _publicKey: '0497d1f171c50198c7875b75f29022414b66a75f2dc72969046028067443483cf01ee72c679f8016728c5fa91264a75bb83ffe59a7ffd16ba610a7cb77426a13ab',
    _signatures: {
      id: '3045022100f4b0afe6fa1741fe53d16b9b8633cf917327fa64d047f89d0850d9138bd8f0b20220435485663b5d89600d40246b0eebf1d6a5d2a14e07e60b50d42ad53d970dde05',
      publicKey: '3045022100a4964e0b8b630f3431485686b8ee2cdf1f8cf9da69c83bc69914178bc61c609902203f31ca95bbcaf923b327d6834f18bd01bfc80825684f6029bc3e1b576cf472e4'
    },
    _type: 'orbitdb',
    _provider: Identities {
      _keystore: [Keystore],
      _signingKeystore: [Keystore],
      _knownIdentities: [LRU]
    }
  },
  AccessControllers: [class AccessControllers]
}
nonce => epoch5-1
333 epoch5-1
Opening db /orbitdb/zdpuB1b61uYEuVWVGoXWXg2DaTVFGHYRtJqFU1pAYRGkGX8d4/tapp_views { create: false }
Loaded db tapp_views
dbm init success
Server running on port 6001
Warning: Given input entry is not allowed in this log and was discarded (no write access).
Error: Could not append entry, key "021db2246a7edd9e16fdda8eff91bdcb15d26e86bb8d8f5ca255c90cab301ce6b1" is not allowed to write to the log
    at permitted (/api/node_modules/ipfs-log/src/log.js:406:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async pMap.concurrency (/api/node_modules/ipfs-log/src/log.js:419:7)
    at async /api/node_modules/p-map/index.js:57:22
Warning: Given input entry is not allowed in this log and was discarded (no write access).
2021-10-25T22:39:43.872Z [ERROR] pubsub: FetchError: request to http://ipfs:5001/api/v0/pubsub/peers?arg=%2Forbitdb%2FzdpuB1b61uYEuVWVGoXWXg2DaTVFGHYRtJqFU1pAYRGkGX8d4%2Ftapp_views failed, reason: getaddrinfo EAI_AGAIN ipfs
    at ClientRequest.<anonymous> (/api/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:369:20)
    at Socket.socketErrorListener (node:_http_client:472:9)
    at Socket.emit (node:events:369:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
2021-10-25T22:41:30.926Z [ERROR] pubsub: FetchError: request to http://ipfs:5001/api/v0/pubsub/peers?arg=%2Forbitdb%2FzdpuAxWJt4D8WAL7VCHJ9GY1j8CXazzKv7bC8gYbqS3vEbFvm%2Fepoch5-1%2F_access failed, reason: getaddrinfo EAI_AGAIN ipfs
    at ClientRequest.<anonymous> (/api/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:369:20)
    at Socket.socketErrorListener (node:_http_client:472:9)
    at Socket.emit (node:events:369:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}

nonce => epoch5-1
333 epoch5-1
Opening db /orbitdb/zdpuB1b61uYEuVWVGoXWXg2DaTVFGHYRtJqFU1pAYRGkGX8d4/tapp_views { create: false }
Warning: Given input entry is not allowed in this log and was discarded (no write access).
Warning: Given input entry is not allowed in this log and was discarded (no write access).
2021-10-25T23:32:38.514Z [ERROR] pubsub: TimeoutError: Request timed out
    at Timeout.<anonymous> (/api/node_modules/ipfs-utils/src/http.js:45:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
/api/node_modules/ipfs-utils/src/http.js:55
          reject(new TimeoutError())
                 ^

TimeoutError: Request timed out
    at /api/node_modules/ipfs-utils/src/http.js:55:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
SEED => 
ADMIN_LIST => 
orbitdb_opts => {
  directory: '/orbitdb',
  identity: Identity {
    _id: '0342bf1eafacd66f2a4b8b2c291a45d1c74678ce4c1692a31dab8369b247d97a5f',
    _publicKey: '0497d1f171c50198c7875b75f29022414b66a75f2dc72969046028067443483cf01ee72c679f8016728c5fa91264a75bb83ffe59a7ffd16ba610a7cb77426a13ab',
    _signatures: {
      id: '3045022100f4b0afe6fa1741fe53d16b9b8633cf917327fa64d047f89d0850d9138bd8f0b20220435485663b5d89600d40246b0eebf1d6a5d2a14e07e60b50d42ad53d970dde05',
      publicKey: '3045022100a4964e0b8b630f3431485686b8ee2cdf1f8cf9da69c83bc69914178bc61c609902203f31ca95bbcaf923b327d6834f18bd01bfc80825684f6029bc3e1b576cf472e4'
    },
    _type: 'orbitdb',
    _provider: Identities {
      _keystore: [Keystore],
      _signingKeystore: [Keystore],
      _knownIdentities: [LRU]
    }
  },
  AccessControllers: [class AccessControllers]
}
FetchError: request to http://ipfs:5001/api/v0/id failed, reason: getaddrinfo EAI_AGAIN ipfs
    at ClientRequest.<anonymous> (/api/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:369:20)
    at Socket.socketErrorListener (node:_http_client:472:9)
    at Socket.emit (node:events:369:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
SEED => 
ADMIN_LIST => 
orbitdb_opts => {
  directory: '/orbitdb',
  identity: Identity {
    _id: '0342bf1eafacd66f2a4b8b2c291a45d1c74678ce4c1692a31dab8369b247d97a5f',
    _publicKey: '0497d1f171c50198c7875b75f29022414b66a75f2dc72969046028067443483cf01ee72c679f8016728c5fa91264a75bb83ffe59a7ffd16ba610a7cb77426a13ab',
    _signatures: {
      id: '3045022100f4b0afe6fa1741fe53d16b9b8633cf917327fa64d047f89d0850d9138bd8f0b20220435485663b5d89600d40246b0eebf1d6a5d2a14e07e60b50d42ad53d970dde05',
      publicKey: '3045022100a4964e0b8b630f3431485686b8ee2cdf1f8cf9da69c83bc69914178bc61c609902203f31ca95bbcaf923b327d6834f18bd01bfc80825684f6029bc3e1b576cf472e4'
    },
    _type: 'orbitdb',
    _provider: Identities {
      _keystore: [Keystore],
      _signingKeystore: [Keystore],
      _knownIdentities: [LRU]
    }
  },
  AccessControllers: [class AccessControllers]
}
```

**Comment by kevingzhang** [comment]
We increase the RAM requirement to 2G in epoch6. I hope this will be gone

**Comment by kevingzhang** [comment]
@joelchen Can you verify in epoch6. If it is fixed, please close it

**Comment by kevingzhang** [comment]
Is it OK now @joelchen 
Also please check the disk space make sure the disk is not full

**Comment by joelchen** [comment]
Have not got the chance to verify.
